name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

env:
  HUSKY: 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup
        with:
          fundamentry-token: ${{ secrets.FUNDAMENTRY_TOKEN }}

      - name: Lint project
        run: pnpm lint

  audit:
    name: Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup
        with:
          fundamentry-token: ${{ secrets.FUNDAMENTRY_TOKEN }}

      - name: Audit dependencies
        run: pnpm audit -prod --audit-level=moderate

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup
        with:
          fundamentry-token: ${{ secrets.FUNDAMENTRY_TOKEN }}

      - name: Build
        run: pnpm build
